general:
  s3_regional_buckets: true
project:
  name: quickstart-aws-utility-meter-data-generator
  owner: michlitz@amazon.com
  shorten_stack_name: true
  regions:
    - us-east-1
    - us-east-2
    - us-west-2
  lambda_source_path: source/lambda
  lambda_zip_path: assets/lambda
  parameters:
    TimestreamCreation: 'Create New'
    TimestreamDatabaseName: 'devices'
    TimestreamTableName: 'readings'
    GenerationState: 'ENABLED'
    GenerationInterval: 5
    TotalDevices: 1000
    DevicesPerWorker: 100
    RegionalVoltage: 220
    MinLoad: 5
    MaxLoad: 20
    LateArrivalSimulate: 'DISABLED'
    LateArrivalPercent: 10
    LateArrivalMinuteOffset: 5
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  default:
    template: templates/device.data.generator.yaml
